### PR TITLE
✨ added CSRF attack detection

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by ghost** [comment]
Oh neat, this also has the added benefit, that refreshing the "/api/discord/callback" page, right after authorization, won't send any additional requests to Discord and just fail. Should I add a note to the comments or possibly even adjust the error handling, so it silently rejects the request instead of claiming it was a CSRF attack?

**Comment by KrishGarg** [comment]
Yeah silently rejecting the request should be fine.

**Comment by ghost** [comment]
Alright, I think this is reasonably silent now. I'll adjust the clean branches for you too, I just need to set up my dev environment first.

**Comment by KrishGarg** [comment]
It's fine, I can adjust the clean branch.
Thank you very much for the help!

**Comment by KrishGarg** [comment]
By the way, for the future, we can just copy paste the index.js from master to clean and github will clean it automatically after pushing.

**Pull request merged**
